Qrisp sat solver
ProvideQ/toolbox-server pull request #100
Opened 2024-11-04 12:15 UTC by tubadzin

Qrisp-grover-sat solver implementation. Still contains some todo's:

1. Resolve timeout error in satProblemSolver and createProblem methods in ApiTestHelper.
2. Resolve NullPointerException in SatBasedDeadFeatureSolver (getSolutionData() Method) - exact variant of grover would solve this problem, sadly it requires calculating the number of all valid solutions, which is as hard as solving sat itself).

2024-12-15 15:12 UTC, tubadzin commented
# Intro

Unfortunately, this branch has quickly spiraled out of control due to the number of changes I have made. This serves as a prime example of the sunk cost fallacy.

Here’s a brief recap of the changes:

## Changes

### `sat.py` and the corresponding `QrispSatSolver.java` class
A detailed explanation of what is happening can be found in the `qrisp_sat_utils.py` script, specifically in the comments for the `sat_oracle` method.

### `exact_sat.py` and the corresponding `ExactQrispSatSolver` class
This variant utilizes (almost) the same logic as the default `QrispSatSolver`. The key difference is that this version (in theory) avoids considering impossible variable assignments. For this, the Oracle needs to know the size of the solution space.

### `sharp-sat-solver`
As mentioned above, `exact_sat.py` requires the size of the solution space to function correctly. To address this, I have added a Linux binary that, given a `.cnf` file, approximates the number of solutions. Unfortunately, this approximation fails in trivial cases where the `.cnf` file is unsatisfiable, such as:

```
p cnf 1 2
1 0
-1 0
```

This case should obviously return `0`, but the solver instead returns `1` or `2` (if pre-processing is disabled). The issue arises because the solver simplifies contradictory clauses, and once removed, the remaining formula is interpreted as having no constraints, allowing `x` to take any value (both true and false).

Additionally, I attempted to compile this program for Windows, but to no avail. Both cross-compiling and building it on my Windows machine failed. This led me down a long rabbit hole where I replaced platform-dependent code iteratively. While I eventually managed to build an `.exe`, it still produced errors when running. I have yet to find another SharpSAT solver that works on Windows. Some alternatives I considered are:
- [sharpSAT](https://github.com/marcthurley/sharpSAT)
- [d4](https://github.com/crillab/d4v2)
- [sharpSAT-TD](https://github.com/Laakeri/sharpsat-td)
- [miniC2D](http://reasoning.cs.ucla.edu/minic2d/)
- [Ganak](https://github.com/meelgroup/ganak)
- [approxmc](https://github.com/meelgroup/approxmc)

### Update to Debian 12
The container was unable to run on the latest Debian image because the SharpSAT binary requires `glibc` version 2.33 or later. Debian 12 provides version 2.36, whereas Debian 11 provides only 2.31. I initially attempted to include a prebuilt version of `glibc` in the project files and link it to the appropriate paths in the Docker container, but this resulted in numerous errors. Ultimately, I opted for a distribution update instead.

### Exclusion of Quantum SAT Solvers in the dead/anomaly tests
The `QrispSatSolver` has a notable issue: in cases such as:

```
p cnf 1 2
1 0
-1 0
```

It outputs a result indicating a 50% probability of true and a 50% probability of false assignments. I attempted to differentiate between cases where both assignments (true and false) are valid versus cases that are outright impossible using SharpSAT—by checking if the number of solutions is greater than 0. However, this approach is unreliable due to inconsistencies in SharpSAT's output. Since SAT solving is NP-hard, using exact solvers without approximators is impractical.

Anomaly tests take as input a `featureModelSolver`, `problemType`, `input`, and `satSolver`. In these tests, SAT solvers are used as subroutines on the given feature model. Because of this, it is difficult to hand-pick small examples that would run correctly on the quantum simulation—and even if they did, the results would likely be incorrect. Consequently, I decided to exclude `QrispSatSolvers` entirely from these tests.

---

## Problems & Questions
1. **Code Duplication:**  
   SonarCloud code analysis reports 27.5% code duplication between `sat.py` and `exact_sat.py`. While I could artificially remove the duplications, I believe the code is currently more readable as it is. Should I prioritize readability or reduce duplication?

2. **SharpSAT on Windows:**  
   What should I do about the lack of a working SharpSAT binary for Windows?

2025-01-13 10:11 UTC, tubadzin commented
### Meeting notes 13.01.24

- Split exact Grover, approximate Grover and CI / CD changes into different branches
- Change SonarCloud restrictions. They are at times too limiting - in this case would lead to less readable code.
- Domenik and me scheduled a separate meeting. The goal is to think about if the exact groover approach is needed, especially if the needed sharpSAT dependency is faulty and does not yield the wanted solutions.

2025-01-13 12:14 UTC, tubadzin commented
This PR is now complemented by:
- Update Docker Image #111 
- Add Sharp SAT Variant #112 
- Add Exact Qrisp SAT Solver Variant #113 

Although both this issue and #113 are similar, the latter has required changes in dependencies, extra binaries and deeper changes to the project. For simplicity and good structure, they are now separated.

2025-01-14 15:13 UTC, koalamitice requested changes
Looks good. I would prefer to have the small naming changes included, then its ready to merge. I will write a reminder that we improve the names of the other solvers aswell...
I just looked them up for reference... :D

2025-01-14 15:13 UTC, koalamitice commented on src/main/java/edu/kit/provideq/toolbox/sat/solvers/QrispSatSolver.java
> +    return "QRISP SAT";
I would prefer a more descriptive name (we messed this up at some other solvers aswell).
How about "Grover-Search (Qrisp)"

2025-01-14 15:13 UTC, koalamitice commented on src/main/resources/application.properties
> +qrisp.script.sat=${qrisp.directory}/sat/sat.py
Maybe name this "grover" and the exact one "exact_grover" (cause sat is specified in the parent directory)

2025-01-21 12:39 UTC, koalamitice approved these changes

2025-01-21 12:40 UTC, merged