Generics Cleanup
ProvideQ/toolbox-server pull request #34
Opened 2023-06-30 11:01 UTC by Elscrux

Attempt to fix most of the issues with raw generics.
`SubRoutinePool` still has issues with casting to the right `ProblemControllerProvider`. If you have an idea how to fix that, let me know @schweikart.

2023-07-19 19:12 UTC, schweikart requested changes

2023-07-28 11:51 UTC, schweikart commented on src/main/java/edu/kit/provideq/toolbox/featuremodel/anomaly/MetaSolverFeatureModelAnomaly.java
> +        edu.kit.provideq.toolbox.featuremodel.anomaly.FeatureModelAnomalyProblem,
same problem in line 29

2023-07-28 11:54 UTC, schweikart commented
Can you rebase onto `develop`?

2023-07-28 12:36 UTC, Elscrux commented on src/main/java/edu/kit/provideq/toolbox/featuremodel/anomaly/MetaSolverFeatureModelAnomaly.java
> +        edu.kit.provideq.toolbox.featuremodel.anomaly.FeatureModelAnomalyProblem,
Yeah, sorry I'm blind

2023-07-28 12:38 UTC, Elscrux commented
@schweikart I rebased the branch

2023-07-29 20:22 UTC, schweikart approved these changes

2023-07-29 20:22 UTC, merged