Make DimacsCnf constructors copy deeply
ProvideQ/toolbox-server pull request #36
Opened 2023-06-30 11:25 UTC by Elscrux

2023-07-07 08:47 UTC, schweikart requested changes

2023-07-07 08:47 UTC, schweikart commented on src/main/java/edu/kit/provideq/toolbox/format/cnf/dimacs/DimacsCnf.java
> +                    .collect(Collectors.toCollection(ArrayList::new)))
please apply the DRY principle here and extract the List<Variable> copying to its own (private) function

2023-07-07 08:47 UTC, schweikart commented on src/main/java/edu/kit/provideq/toolbox/format/cnf/dimacs/Variable.java
> +
Please document new public methods so we don't pile up new documentation debt

2023-07-08 12:37 UTC, Elscrux commented
@schweikart I have included your suggestions

2023-07-12 11:42 UTC, schweikart approved these changes
LGTM! :)

2023-07-12 11:42 UTC, merged