Refactor controllers to avoid boilerplate code
ProvideQ/toolbox-server pull request #39
Opened 2023-07-30 21:39 UTC by schweikart

This pull request replaces our controllers with a generic router implementation that discovers and routes new meta solvers (problem types) automatically.

2023-08-01 14:58 UTC, schweikart commented
Feature Model tests are currently failing because the feature model anomaly solver currently does not use the same route structure as the other solvers. We can solve this problem by separating all feature model anomalies into different problem types (implemented in #40 ) or by combining the feature model anomaly routes into a single route and adding an `AnomalyType` parameter to  `FeatureModelAnomalyRequest`.

2023-08-06 08:45 UTC, Elscrux commented
Cross Origin is still a problem here, and we'll have to sort that out for the new webflux framework.

2023-08-06 09:51 UTC, Elscrux requested changes
Looks good so far! The functional approach really shines here.
I think we could move the documentation part to its own method in each class, similarly to the handle method. That would separate this part a bit, reduce nesting and the method name would also help to document what this is for (I first didn't really get what this is about until you told me).

2023-08-06 09:51 UTC, Elscrux commented on src/main/java/edu/kit/provideq/toolbox/api/SolveRouter.java
> +    // No idea why `toStringSolution` returns `SolutionHandle`
Probably in a misguided effort to use the type with the fewest assumptions. Feel free to change that.

2023-09-02 20:05 UTC, schweikart commented
> Looks good so far! The functional approach really shines here. I think we could move the documentation part to its own method in each class, similarly to the handle method. That would separate this part a bit, reduce nesting and the method name would also help to document what this is for (I first didn't really get what this is about until you told me).

That seems like a good idea! Can you address this in your PR for API documentation?

2023-09-03 10:49 UTC, Elscrux commented
> Cross Origin is still a problem here, and we'll have to sort that out for the new webflux framework.

Tested again with the latest versions of the web (merged PR) and toolbox (anomaly refactor), this should have been fixed.

2023-09-03 10:51 UTC, Elscrux commented
> > Looks good so far! The functional approach really shines here. I think we could move the documentation part to its own method in each class, similarly to the handle method. That would separate this part a bit, reduce nesting and the method name would also help to document what this is for (I first didn't really get what this is about until you told me).
> 
> That seems like a good idea! Can you address this in your PR for API documentation?

Yeah I can do that as part of the API documentation.

2023-09-03 10:51 UTC, Elscrux commented on src/main/java/edu/kit/provideq/toolbox/api/SolveRouter.java
> +        "/solve/" + problemId,
This is still a thing right? You just have two function calls right now.

2023-09-03 11:55 UTC, Elscrux commented on src/main/java/edu/kit/provideq/toolbox/api/SolveRouter.java
> +        "/solve/" + problemId,
Nevermind, in my API refactoring I'll need to call things from two different methods anyway. And this is not a huge deal. It's good that the magic string is only used once in a central place now.

2023-09-03 11:56 UTC, Elscrux approved these changes
This all looks fine to me now, but I'll wait for your SolutionHandle removal (if you want to do that, and do it in this PR)

2023-09-07 10:57 UTC, schweikart commented
> This all looks fine to me now, but I'll wait for your SolutionHandle removal (if you want to do that, and do it in this PR)

I'll do that in another PR but please merge #40 before merging this one :)

2023-09-08 20:20 UTC, merged