Refactor: split up feature model anomaly solver into different anomalies
ProvideQ/toolbox-server pull request #40
Opened 2023-08-01 12:23 UTC by schweikart

2023-08-06 10:00 UTC, Elscrux requested changes
The separate feature model solvers are much better now. Since we are using the Webflux framework now, the only real overhead of this approach is the additional meta solver, which is valid and perhaps even desired.

2023-08-06 11:06 UTC, schweikart commented
> the only real overhead of this approach is the additional meta solver, which is valid and perhaps even desired.

We might even be able to get rid of that. We could implement an ` abstract SingletonProblemSolver extends ProblemSolver implements MetaSolver` that implements the `MetaSolver` methods automatically. This could be used for problems with only a single solver.

2023-08-06 11:07 UTC, schweikart commented on src/main/java/edu/kit/provideq/toolbox/featuremodel/anomaly/voidmodel/VoidFeatureMetaSolver.java
> +  private final VoidFeatureSolver solver;
agreed, I struggled to come up with a precise name. `SatBasedVoidFeatureModelMetaSolver` would be precise but I'm not sure if it's too long...

2023-08-06 11:09 UTC, schweikart commented on src/main/java/edu/kit/provideq/toolbox/featuremodel/anomaly/dead/DeadFeatureMetaSolver.java
> +  private final DeadFeatureSolver solver = new DeadFeatureSolver();
That wasn't intended, it's probably a result of IntelliJ's autocompletion... I'll change it

2023-08-06 11:09 UTC, schweikart commented on src/main/java/edu/kit/provideq/toolbox/meta/ProblemType.java
>    FEATURE_MODEL_ANOMALY("feature-model-anomaly", SolveFeatureModelRequest.class),
nope, I'll remove it

2023-08-06 11:10 UTC, schweikart commented on src/main/java/edu/kit/provideq/toolbox/featuremodel/anomaly/dead/DeadFeatureMetaSolver.java
> +  private final DeadFeatureSolver solver = new DeadFeatureSolver();
Maybe `SatBasedDeadFeatureMetaSolver`?

2023-08-06 11:10 UTC, schweikart commented on src/main/java/edu/kit/provideq/toolbox/featuremodel/anomaly/voidmodel/VoidFeatureSolver.java
> +        new SubRoutineDefinition(ProblemType.SAT, "sat",
good point!

2023-08-06 11:10 UTC, Elscrux commented
> We might even be able to get rid of that. We could implement an ` abstract SingletonProblemSolver extends ProblemSolver implements MetaSolver` that implements the `MetaSolver` methods automatically. This could be used for problems with only a single solver.

I'd rather keep it as it is, as a `SingletonProblemSolver` kind of goes against the point of a `MetaSolver` which should handle multiple solvers. We might not want to create another solver for something like a dead features anomaly in feature models, but at least we support it.

2023-08-06 11:12 UTC, Elscrux commented on src/main/java/edu/kit/provideq/toolbox/featuremodel/anomaly/dead/DeadFeatureMetaSolver.java
> +  private final DeadFeatureSolver solver = new DeadFeatureSolver();
Yeah, that's not very pretty but is more descriptive

2023-08-06 11:15 UTC, Elscrux commented on src/main/java/edu/kit/provideq/toolbox/featuremodel/anomaly/voidmodel/VoidFeatureMetaSolver.java
> +  private final VoidFeatureSolver solver;
It's quite long, but I can't imagine anything else that's better. You could abbreviate some parts of the name (like FeatureModel -> FM), but that's also not very nice. So I'd say use that.

2023-09-02 21:17 UTC, schweikart commented
I've fixed toolbox-web to use this new route scheme in https://github.com/ProvideQ/toolbox-web/pull/25

2023-09-03 10:43 UTC, Elscrux commented on src/main/java/edu/kit/provideq/toolbox/meta/ProblemType.java
>    FEATURE_MODEL_ANOMALY("feature-model-anomaly", SolveFeatureModelRequest.class),
I don't think this is fixed yet?

2023-09-03 10:43 UTC, Elscrux commented on src/main/java/edu/kit/provideq/toolbox/featuremodel/anomaly/voidmodel/VoidFeatureSolver.java
> +        new SubRoutineDefinition(ProblemType.SAT, "sat",
I don't think this is fixed yet?

2023-09-03 10:46 UTC, Elscrux commented on src/main/java/edu/kit/provideq/toolbox/featuremodel/anomaly/dead/DeadFeatureMetaSolver.java
> +  private final DeadFeatureSolver solver = new DeadFeatureSolver();
I don't think this is fixed yet?

2023-09-03 10:46 UTC, Elscrux commented on src/main/java/edu/kit/provideq/toolbox/featuremodel/anomaly/dead/DeadFeatureMetaSolver.java
> +  private final DeadFeatureSolver solver = new DeadFeatureSolver();
I don't think this is fixed yet?

2023-09-07 10:25 UTC, schweikart commented on src/main/java/edu/kit/provideq/toolbox/featuremodel/anomaly/dead/DeadFeatureMetaSolver.java
> +  private final DeadFeatureSolver solver = new DeadFeatureSolver();
Now it is, I haven't gotten to revising this PR until now

2023-09-07 10:56 UTC, schweikart commented
I've finally gotten to revising this PR now :sweat_smile: 

If this works for you now, please merge this PR into `refactor/controllers` first so the tests over there pass as well. Then we can merge #39 as well :)

2023-09-07 11:36 UTC, Elscrux commented on src/main/java/edu/kit/provideq/toolbox/meta/SubRoutineDefinition.java
> +public record SubRoutineDefinition(ProblemType type, String description) {
We still need the url as part of the record. See here for its usage: https://github.com/ProvideQ/toolbox-web/blob/develop/src/components/solvers/SolverPicker.tsx#L123

What we should do here instead is only require the problem type and description in the constructor for `SubRoutineDefinition` so the url part can be inferred from the type.

2023-09-08 20:13 UTC, merged